
---
- name: Create imalive docker-compose file
  become: yes
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ item.path }}/{{ item.template }}"
    mode: "{{ item.mode }}"
  with_items:
    - { template: docker-compose-imalive.yml , path: "{{ node_home }}", mode: '0644' }
    - { template: .env.imalive , path: "{{ node_home }}", mode: '0644' }
    - { template: imalive.yml , path: "{{ node_home }}", mode: '0644' }
    - { template: imalive_start.sh , path: "{{ node_home }}", mode: '0755' }

- name: Run the container
  become: yes
  command: "bash {{ node_home }}/imalive_start.sh"
