version: "3.3"

services: 
  imalive-api:
    image: comworkio/imalive-api:latest-arm
    container_name: imalive-api
    build: 
      context: .
      dockerfile: Dockerfile.arm
      target: api
    env_file: 
      - .env
    ports: 
      - 8080:8080
