---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  ports:
    - name: "http"
      port: {{ $.Values.service_port }}
      targetPort: 8080
  selector:
    app: {{ include "common.names.fullname" . }}
