
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'imalive'
    static_configs:
      - targets: ['imalive-api:8080']
    metrics_path: '/v1/prom'
    scheme: http
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['otel-collector:8889']
